import React from 'react'
import './globals.css'
import Header from './components/Header';





export const metadata = {
  title: 'BarWa App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}) {
  return (
    

    <body>
        <Header/>
        <main>{children}</main>
        </body>
     
  
      
  
  )}