import Header from "../components/Header";
import '../styles/globals.css'
import NextAuthSessionProvider from "./providers/sessionProvider";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">

      <body>
      <NextAuthSessionProvider>
        <Header />
        {children}
      </NextAuthSessionProvider>
      </body>
    </html>
  );
}
